import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'freshfarm_language';

const translations = {
  en: {
    selectLocation: 'Select Location',
    searchPlaceholder: 'Search fresh products',
    becomeSeller: 'Become a seller',
    login: 'Login',
    signup: 'Signup',
    account: 'Account',
    cart: 'Cart',
    addresses: 'Addresses',
    myOrders: 'My Orders',
    customerSupport: 'Customer Support',
    manageReferrals: 'Manage Referrals',
    accountProfile: 'Profile',
    walletTitle: 'FreshFarm Cash & Gift Card',
    availableBalance: 'Available Balance',
    addBalance: 'Add Balance',
    currencySymbol: 'Rs ',
    noSpamPromise: 'We promise not to spam you',
    submit: 'Submit',
    deleteAccount: 'Delete Account',
    deleteAccountNote: 'Deleting your account will remove your orders, wallet balance and active referrals.',
    ordersComingSoon: 'Your latest orders will appear here soon.',
    supportHelpText: 'Need help? Contact support from this section.',
    referralHelpText: 'Referral rewards and sharing options will show here.',
    addressHelpText: 'Manage saved delivery addresses here.',
    profileSaved: 'Profile updated successfully.',
    profileSaveFailed: 'Could not update profile. Please try again.',
    customerNameFallback: 'FreshFarm Customer',
    orderId: 'Order ID',
    orderStatus: 'Order Status',
    addressLabel: 'Address Label',
    setDefaultAddress: 'Set as default address',
    saveAddress: 'Save Address',
    amount: 'Amount',
    supportSubject: 'Support Subject',
    supportMessage: 'Describe your issue',
    submitTicket: 'Submit Ticket',
    noSupportTickets: 'No support tickets yet.',
    referralCode: 'Referral Code',
    invitedFriends: 'Invited Friends',
    referralEarnings: 'Referral Earnings',
    simulateReferral: 'Add Test Referral',
    logout: 'Logout',
    language: 'Language',
    welcomeTo: 'Welcome to',
    createAccount: 'Create your account',
    signUp: 'Sign Up',
    signIn: 'Signing in...',
    continueWithGoogle: 'Continue with Google',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    becomeASeller: 'Become a Seller',
    fullName: 'Full Name',
    email: 'Email',
    phoneNumberField: 'Phone Number',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    enterOtp: 'Enter OTP',
    verifyOtp: 'Verify OTP',
    signInButton: 'Login',
    otpSent: 'An OTP has been sent to your email.',
    otpPrompt: 'We sent a verification code to',
    support: 'Support',
    helpCenter: 'Help Center',
    liveChat: 'Live Chat',
    orderStatus: 'Check Order Status',
    refunds: 'Refunds',
    reportAbuse: 'Report Abuse',
    productsSection: 'Products',
    sellOnFreshFarms: 'Sell on Fresh Farms',
    tradeAssurance: 'Trade Assurance',
    getToKnowUs: 'Get to Know Us',
    connectWithUs: 'Connect with Us',
    dashboard: 'Dashboard',
    totalProducts: 'Total Products',
    totalOrders: 'Total Orders',
    totalFarmers: 'Total Farmers',
    totalUsers: 'Total Users',
    totalInventory: 'Total Inventory',
    totalSales: 'Total Sales',
    fromLastMonth: 'from last month',
    lastMonthLabel: 'Last month',
    adminManagement: 'Admin Management',
    admins: 'Admins',
    create: 'Create',
    farmers: 'Farmers',
    customers: 'Customers',
    inventory: 'Inventory',
    inquiries: 'Inquiries',
    productsNav: 'Products',
    ordersNav: 'Orders',
    fullNameLabel: 'Full Name',
    contactInfo: 'Contact Info',
    messageLabel: 'Message',
    searchProducts: 'Search products...',
    allStock: 'All Stock',
    lowStock: 'Low Stock',
    highStock: 'High Stock',
    productName: 'Product Name',
    productCategory: 'Product Category',
    productId: 'Product ID',
    productPrice: 'Product Price',
    productQuantity: 'Product Quantity',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    editQuantity: 'Edit Quantity',
    farmersManagement: 'Farmer Management',
    searchFarmerName: 'Search by farmer name',
    editFarmer: 'Edit Farmer',
    deleteFarmerConfirm: 'Are you sure you want to delete this farmer?',
    capitalNameValidation: 'Name must start with a capital letter.',
    emailAtValidation: "Email must contain '@'.",
    phoneValidation: 'Phone number must be numeric and 10 digits long.',
    save: 'Save',
    cancel: 'Cancel',
    ok: 'OK',
    areYouSureDeleteProduct: 'Are you sure you want to delete this product?',
    yes: 'Yes',
    no: 'No',
    addProduct: 'Add Product',
    description: 'Description',
    categoryLabel: 'Category',
    priceLabel: 'Price',
    quantityLabel: 'Quantity',
    imageLabel: 'Image',
    nameHindiLabel: 'Name (Hindi)',
    nameTeluguLabel: 'Name (Telugu)',
    nameLabel: 'Name',
    selectCategory: 'Select Category',
    pleaseFillAllFields: 'Please fill in all fields.',
    nameMustStartCapital: 'Name must start with a capital letter.',
    enterNumericValue: 'Please enter a numeric value.',
    fruits: 'Fruits',
    vegetables: 'Vegetables',
    dairyProducts: 'Dairy Products',
    grains: 'Grains',
    spices: 'Spices',
    organic: 'Organic',
    startSelling: 'Start Selling',
    sellerCentral: 'Seller Central',
    verifiedSeller: 'Become a Verified Seller',
    partnerships: 'Partnerships',
    safePayments: 'Safe and Easy Payments',
    moneyBackPolicy: 'Money-back Policy',
    onTimeShipping: 'On-time Shipping',
    productMonitoring: 'Product Monitoring Services',
    cashOnDelivery: 'Cash on Delivery',
    aboutFreshFarms: 'About Fresh Farms',
    bestPrices: 'Best prices & offers',
    freeDelivery: 'Free delivery',
    greatDailyDeal: 'Great daily deal',
    wideAssortment: 'Wide assortment',
    easyReturns: 'Easy returns',
    orders50: 'Orders $50 or more',
    inquiryTitle: 'We will get in touch with you shortly',
    firstName: 'First Name',
    lastName: 'Last Name',
    contactNumber: 'Contact Number',
    message: 'Message',
    send: 'Send',
    messageSent: 'Message Sent!',
    inquiryThanks: 'Thank you for your inquiry regarding',
    loading: 'Loading...',
    exploreFreshProducts: 'Explore Fresh Products',
    noProductsFound: 'No products found.',
    price: 'Price',
    category: 'Category',
    availability: 'Availability',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    kilogram: 'Kilogram',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    inquiry: 'Inquiry',
    addedToCartSuccess: 'Added to cart successfully!',
    goToCart: 'Go to Cart',
    cartEmpty: 'Cart is empty',
    quantity: 'Quantity',
    remove: 'Remove',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    shippingFee: 'Shipping Fee',
    total: 'Total',
    proceedToCheckout: 'Proceed to Checkout',
    checkout: 'Checkout',
    name: 'Name',
    phoneNumber: 'Phone Number',
    pinAddressOnMap: 'Pin your address on the map',
    useCurrentLocation: 'Use Current Location',
    addressDetails: 'Address Details',
    addressPlaceholder: 'Tap on the map or type your full address...',
    placeOrder: 'Place Order',
    orderPlaced: 'Your order has been placed successfully!',
    goHome: 'Go back to home',
    deliveryLocation: 'Delivery Location',
    joinAsRider: 'Join as Rider',
    riderLogin: 'Delivery Partner Login',
    consumerFarmerLogin: 'Consumer / Farmer Login'
  },
  hi: {
    selectLocation: 'स्थान चुनें',
    searchPlaceholder: 'ताज़े उत्पाद खोजें',
    becomeSeller: 'विक्रेता बनें',
    login: 'लॉगिन',
    signup: 'साइन अप',
    account: 'खाता',
    cart: 'कार्ट',
    addresses: 'पते',
    myOrders: 'मेरे ऑर्डर',
    customerSupport: 'ग्राहक सहायता',
    manageReferrals: 'रेफरल प्रबंधन',
    accountProfile: 'प्रोफाइल',
    walletTitle: 'FreshFarm कैश और गिफ्ट कार्ड',
    availableBalance: 'उपलब्ध बैलेंस',
    addBalance: 'बैलेंस जोड़ें',
    currencySymbol: 'रु ',
    noSpamPromise: 'हम आपको स्पैम नहीं करेंगे',
    submit: 'सबमिट',
    deleteAccount: 'खाता हटाएं',
    deleteAccountNote: 'खाता हटाने पर आपके ऑर्डर, वॉलेट बैलेंस और सक्रिय रेफरल हट जाएंगे।',
    ordersComingSoon: 'आपके हाल के ऑर्डर यहां दिखेंगे।',
    supportHelpText: 'मदद चाहिए? इस सेक्शन से सपोर्ट से संपर्क करें।',
    referralHelpText: 'रेफरल रिवॉर्ड और शेयर विकल्प यहां दिखेंगे।',
    addressHelpText: 'यहां अपने सेव किए गए डिलीवरी पते प्रबंधित करें।',
    profileSaved: 'प्रोफाइल सफलतापूर्वक अपडेट हुई।',
    profileSaveFailed: 'प्रोफाइल अपडेट नहीं हो सकी। कृपया दोबारा प्रयास करें।',
    customerNameFallback: 'FreshFarm ग्राहक',
    orderId: 'ऑर्डर आईडी',
    orderStatus: 'ऑर्डर स्थिति',
    addressLabel: 'पते का लेबल',
    setDefaultAddress: 'डिफॉल्ट पता बनाएं',
    saveAddress: 'पता सहेजें',
    amount: 'राशि',
    supportSubject: 'सहायता विषय',
    supportMessage: 'अपनी समस्या बताएं',
    submitTicket: 'टिकट जमा करें',
    noSupportTickets: 'अभी तक कोई सहायता टिकट नहीं है।',
    referralCode: 'रेफरल कोड',
    invitedFriends: 'आमंत्रित दोस्त',
    referralEarnings: 'रेफरल कमाई',
    simulateReferral: 'टेस्ट रेफरल जोड़ें',
    logout: 'लॉगआउट',
    language: 'भाषा',
    welcomeTo: 'स्वागत है',
    createAccount: 'अपना खाता बनाएं',
    signUp: 'साइन अप',
    signIn: 'साइन इन हो रहा है...',
    continueWithGoogle: 'Google के साथ जारी रखें',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से खाता है?',
    becomeASeller: 'विक्रेता बनें',
    fullName: 'पूरा नाम',
    email: 'ईमेल',
    phoneNumberField: 'फ़ोन नंबर',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    enterOtp: 'OTP दर्ज करें',
    verifyOtp: 'OTP सत्यापित करें',
    signInButton: 'लॉगिन',
    otpSent: 'आपके ईमेल पर OTP भेज दिया गया है।',
    otpPrompt: 'हमने एक सत्यापन कोड भेजा है',
    support: 'सहायता',
    helpCenter: 'सहायता केंद्र',
    liveChat: 'लाइव चैट',
    orderStatus: 'ऑर्डर स्थिति देखें',
    refunds: 'रिफंड',
    reportAbuse: 'दुरुपयोग रिपोर्ट करें',
    productsSection: 'उत्पाद',
    sellOnFreshFarms: 'Fresh Farms पर बेचें',
    tradeAssurance: 'ट्रेड एश्योरेंस',
    getToKnowUs: 'हमारे बारे में जानें',
    connectWithUs: 'हमसे जुड़ें',
    dashboard: 'डैशबोर्ड',
    totalProducts: 'कुल उत्पाद',
    totalOrders: 'कुल ऑर्डर',
    totalFarmers: 'कुल किसान',
    totalUsers: 'कुल उपयोगकर्ता',
    totalInventory: 'कुल इन्वेंट्री',
    totalSales: 'कुल बिक्री',
    fromLastMonth: 'पिछले महीने से',
    lastMonthLabel: 'पिछला महीना',
    adminManagement: 'एडमिन प्रबंधन',
    admins: 'एडमिन',
    create: 'बनाएं',
    farmers: 'किसान',
    customers: 'ग्राहक',
    inventory: 'इन्वेंट्री',
    inquiries: 'पूछताछ',
    productsNav: 'उत्पाद',
    ordersNav: 'ऑर्डर',
    fullNameLabel: 'पूरा नाम',
    contactInfo: 'संपर्क जानकारी',
    messageLabel: 'संदेश',
    searchProducts: 'उत्पाद खोजें...',
    allStock: 'सभी स्टॉक',
    lowStock: 'कम स्टॉक',
    highStock: 'अधिक स्टॉक',
    productName: 'उत्पाद का नाम',
    productCategory: 'उत्पाद श्रेणी',
    productId: 'उत्पाद आईडी',
    productPrice: 'उत्पाद मूल्य',
    productQuantity: 'उत्पाद मात्रा',
    actions: 'क्रियाएं',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    editQuantity: 'मात्रा संपादित करें',
    farmersManagement: 'किसान प्रबंधन',
    searchFarmerName: 'किसान के नाम से खोजें',
    editFarmer: 'किसान संपादित करें',
    deleteFarmerConfirm: 'क्या आप वाकई इस किसान को हटाना चाहते हैं?',
    capitalNameValidation: 'नाम बड़े अक्षर से शुरू होना चाहिए।',
    emailAtValidation: "ईमेल में '@' होना चाहिए।",
    phoneValidation: 'फ़ोन नंबर संख्यात्मक होना चाहिए और 10 अंक लंबा होना चाहिए।',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    ok: 'ठीक है',
    areYouSureDeleteProduct: 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?',
    yes: 'हाँ',
    no: 'नहीं',
    addProduct: 'उत्पाद जोड़ें',
    description: 'विवरण',
    categoryLabel: 'श्रेणी',
    priceLabel: 'कीमत',
    quantityLabel: 'मात्रा',
    imageLabel: 'छवि',
    nameHindiLabel: 'नाम (हिंदी)',
    nameTeluguLabel: 'नाम (तेलुगु)',
    nameLabel: 'नाम',
    selectCategory: 'श्रेणी चुनें',
    pleaseFillAllFields: 'कृपया सभी फ़ील्ड भरें।',
    nameMustStartCapital: 'नाम बड़े अक्षर से शुरू होना चाहिए।',
    enterNumericValue: 'कृपया संख्यात्मक मान दर्ज करें।',
    fruits: 'फल',
    vegetables: 'सब्जियां',
    dairyProducts: 'डेयरी उत्पाद',
    grains: 'अनाज',
    spices: 'मसाले',
    organic: 'जैविक',
    startSelling: 'बेचना शुरू करें',
    sellerCentral: 'सेलर सेंटर',
    verifiedSeller: 'सत्यापित विक्रेता बनें',
    partnerships: 'साझेदारी',
    safePayments: 'सुरक्षित और आसान भुगतान',
    moneyBackPolicy: 'पैसे वापस नीति',
    onTimeShipping: 'समय पर शिपिंग',
    productMonitoring: 'उत्पाद निगरानी सेवाएं',
    cashOnDelivery: 'कैश ऑन डिलीवरी',
    aboutFreshFarms: 'Fresh Farms के बारे में',
    bestPrices: 'सर्वोत्तम कीमतें और ऑफ़र',
    freeDelivery: 'मुफ़्त डिलीवरी',
    greatDailyDeal: 'बढ़िया दैनिक डील',
    wideAssortment: 'विस्तृत चयन',
    easyReturns: 'आसान रिटर्न',
    orders50: '50 डॉलर या अधिक के ऑर्डर',
    inquiryTitle: 'हम जल्द ही आपसे संपर्क करेंगे',
    firstName: 'पहला नाम',
    lastName: 'अंतिम नाम',
    contactNumber: 'संपर्क नंबर',
    message: 'संदेश',
    send: 'भेजें',
    messageSent: 'संदेश भेज दिया गया!',
    inquiryThanks: 'आपकी पूछताछ के लिए धन्यवाद',
    loading: 'लोड हो रहा है...',
    exploreFreshProducts: 'ताज़े उत्पाद खोजें',
    noProductsFound: 'कोई उत्पाद नहीं मिला।',
    price: 'कीमत',
    category: 'श्रेणी',
    availability: 'उपलब्धता',
    inStock: 'उपलब्ध',
    outOfStock: 'स्टॉक खत्म',
    kilogram: 'किलोग्राम',
    addToCart: 'कार्ट में जोड़ें',
    buyNow: 'अभी खरीदें',
    inquiry: 'पूछताछ',
    addedToCartSuccess: 'उत्पाद कार्ट में जोड़ दिया गया!',
    goToCart: 'कार्ट पर जाएं',
    cartEmpty: 'कार्ट खाली है',
    quantity: 'मात्रा',
    remove: 'हटाएं',
    orderSummary: 'ऑर्डर सारांश',
    subtotal: 'उप-योग',
    shippingFee: 'डिलीवरी शुल्क',
    total: 'कुल',
    proceedToCheckout: 'चेकआउट करें',
    checkout: 'चेकआउट',
    name: 'नाम',
    phoneNumber: 'फ़ोन नंबर',
    pinAddressOnMap: 'मानचित्र पर अपना पता पिन करें',
    useCurrentLocation: 'वर्तमान स्थान उपयोग करें',
    addressDetails: 'पते का विवरण',
    addressPlaceholder: 'मानचित्र पर टैप करें या पूरा पता लिखें...',
    placeOrder: 'ऑर्डर करें',
    orderPlaced: 'आपका ऑर्डर सफलतापूर्वक हो गया!',
    goHome: 'होम पर वापस जाएं',
    deliveryLocation: 'डिलीवरी स्थान',
    joinAsRider: 'राइडर के रूप में जुड़ें',
    riderLogin: 'डिलीवरी पार्टनर लॉगिन',
    consumerFarmerLogin: 'उपभोक्ता / किसान लॉगिन'
  },
  te: {
    selectLocation: 'స్థానాన్ని ఎంచుకోండి',
    searchPlaceholder: 'తాజా ఉత్పత్తులు వెతకండి',
    becomeSeller: 'అమ్మకందారుగా మారండి',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    account: 'ఖాతా',
    cart: 'కార్ట్',
    addresses: 'చిరునామాలు',
    myOrders: 'నా ఆర్డర్లు',
    customerSupport: 'కస్టమర్ సపోర్ట్',
    manageReferrals: 'రిఫరల్స్ నిర్వహణ',
    accountProfile: 'ప్రొఫైల్',
    walletTitle: 'FreshFarm క్యాష్ & గిఫ్ట్ కార్డ్',
    availableBalance: 'అందుబాటులో ఉన్న నిల్వ',
    addBalance: 'బ్యాలెన్స్ జోడించండి',
    currencySymbol: 'రూ ',
    noSpamPromise: 'మేము మీకు స్పామ్ చేయము',
    submit: 'సబ్మిట్',
    deleteAccount: 'ఖాతాను తొలగించండి',
    deleteAccountNote: 'ఖాతాను తొలగిస్తే మీ ఆర్డర్లు, వాలెట్ నిల్వ మరియు యాక్టివ్ రిఫరల్స్ తొలగబడతాయి.',
    ordersComingSoon: 'మీ తాజా ఆర్డర్లు ఇక్కడ త్వరలో కనిపిస్తాయి.',
    supportHelpText: 'సహాయం కావాలా? ఈ విభాగం నుంచి సపోర్ట్‌ను సంప్రదించండి.',
    referralHelpText: 'రిఫరల్ బహుమతులు మరియు షేర్ ఎంపికలు ఇక్కడ కనిపిస్తాయి.',
    addressHelpText: 'సేవ్ చేసిన డెలివరీ చిరునామాలను ఇక్కడ నిర్వహించండి.',
    profileSaved: 'ప్రొఫైల్ విజయవంతంగా అప్డేట్ అయింది.',
    profileSaveFailed: 'ప్రొఫైల్ అప్డేట్ కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    customerNameFallback: 'FreshFarm కస్టమర్',
    orderId: 'ఆర్డర్ ఐడి',
    orderStatus: 'ఆర్డర్ స్థితి',
    addressLabel: 'చిరునామా లేబుల్',
    setDefaultAddress: 'డిఫాల్ట్ చిరునామాగా సెట్ చేయండి',
    saveAddress: 'చిరునామా సేవ్ చేయండి',
    amount: 'మొత్తం',
    supportSubject: 'సపోర్ట్ విషయం',
    supportMessage: 'మీ సమస్యను వివరించండి',
    submitTicket: 'టికెట్ సమర్పించండి',
    noSupportTickets: 'ఇంకా సపోర్ట్ టికెట్లు లేవు.',
    referralCode: 'రిఫరల్ కోడ్',
    invitedFriends: 'ఆహ్వానించిన స్నేహితులు',
    referralEarnings: 'రిఫరల్ ఆదాయం',
    simulateReferral: 'టెస్ట్ రిఫరల్ జోడించండి',
    logout: 'లాగౌట్',
    language: 'భాష',
    welcomeTo: 'స్వాగతం',
    createAccount: 'మీ ఖాతాను సృష్టించండి',
    signUp: 'సైన్ అప్',
    signIn: 'సైన్ ఇన్ అవుతోంది...',
    continueWithGoogle: 'Googleతో కొనసాగించండి',
    dontHaveAccount: 'ఖాతా లేదా?',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    becomeASeller: 'అమ్మకందారుగా మారండి',
    fullName: 'పూర్తి పేరు',
    email: 'ఇమెయిల్',
    phoneNumberField: 'ఫోన్ నంబర్',
    password: 'పాస్వర్డ్',
    confirmPassword: 'పాస్వర్డ్‌ను నిర్ధారించండి',
    enterOtp: 'OTP నమోదు చేయండి',
    verifyOtp: 'OTP ధృవీకరించండి',
    signInButton: 'లాగిన్',
    otpSent: 'మీ ఇమెయిల్‌కు OTP పంపబడింది.',
    otpPrompt: 'మేము ధృవీకరణ కోడ్‌ను పంపాము',
    support: 'సహాయం',
    helpCenter: 'సహాయ కేంద్రం',
    liveChat: 'లైవ్ చాట్',
    orderStatus: 'ఆర్డర్ స్థితి చూడండి',
    refunds: 'రిఫండ్లు',
    reportAbuse: 'దుర్వినియోగాన్ని నివేదించండి',
    productsSection: 'ఉత్పత్తులు',
    sellOnFreshFarms: 'Fresh Farmsలో అమ్మండి',
    tradeAssurance: 'ట్రేడ్ అష్యూరెన్స్',
    getToKnowUs: 'మమ్మల్ని తెలుసుకోండి',
    connectWithUs: 'మాతో కలవండి',
    dashboard: 'డాష్‌బోర్డ్',
    totalProducts: 'మొత్తం ఉత్పత్తులు',
    totalOrders: 'మొత్తం ఆర్డర్లు',
    totalFarmers: 'మొత్తం రైతులు',
    totalUsers: 'మొత్తం వినియోగదారులు',
    totalInventory: 'మొత్తం నిల్వ',
    totalSales: 'మొత్తం అమ్మకాలు',
    fromLastMonth: 'గత నెలతో పోలిస్తే',
    lastMonthLabel: 'గత నెల',
    adminManagement: 'అడ్మిన్ నిర్వహణ',
    admins: 'అడ్మిన్లు',
    create: 'సృష్టించు',
    farmers: 'రైతులు',
    customers: 'వినియోగదారులు',
    inventory: 'నిల్వ',
    inquiries: 'విచారణలు',
    productsNav: 'ఉత్పత్తులు',
    ordersNav: 'ఆర్డర్లు',
    fullNameLabel: 'పూర్తి పేరు',
    contactInfo: 'సంప్రదింపు వివరాలు',
    messageLabel: 'సందేశం',
    searchProducts: 'ఉత్పత్తులు వెతకండి...',
    allStock: 'అన్ని స్టాక్',
    lowStock: 'తక్కువ స్టాక్',
    highStock: 'ఎక్కువ స్టాక్',
    productName: 'ఉత్పత్తి పేరు',
    productCategory: 'ఉత్పత్తి వర్గం',
    productId: 'ఉత్పత్తి ID',
    productPrice: 'ఉత్పత్తి ధర',
    productQuantity: 'ఉత్పత్తి పరిమాణం',
    actions: 'చర్యలు',
    edit: 'సవరించు',
    delete: 'తొలగించు',
    editQuantity: 'పరిమాణం సవరించండి',
    farmersManagement: 'రైతుల నిర్వహణ',
    searchFarmerName: 'రైతు పేరుతో వెతకండి',
    editFarmer: 'రైతును సవరించండి',
    deleteFarmerConfirm: 'ఈ రైతును తొలగించాలనుకుంటున్నారా?',
    capitalNameValidation: 'పేరు పెద్ద అక్షరంతో ప్రారంభం కావాలి.',
    emailAtValidation: "ఇమెయిల్‌లో '@' ఉండాలి.",
    phoneValidation: 'ఫోన్ నంబర్ సంఖ్యాత్మకంగా ఉండాలి మరియు 10 అంకెలు ఉండాలి.',
    save: 'సేవ్',
    cancel: 'రద్దు చేయండి',
    ok: 'సరే',
    areYouSureDeleteProduct: 'ఈ ఉత్పత్తిని తొలగించాలనుకుంటున్నారా?',
    yes: 'అవును',
    no: 'కాదు',
    addProduct: 'ఉత్పత్తి జోడించండి',
    description: 'వివరణ',
    categoryLabel: 'వర్గం',
    priceLabel: 'ధర',
    quantityLabel: 'పరిమాణం',
    imageLabel: 'చిత్రం',
    nameHindiLabel: 'పేరు (హిందీ)',
    nameTeluguLabel: 'పేరు (తెలుగు)',
    nameLabel: 'పేరు',
    selectCategory: 'వర్గాన్ని ఎంచుకోండి',
    pleaseFillAllFields: 'దయచేసి అన్ని ఫీల్డ్‌లు నింపండి.',
    nameMustStartCapital: 'పేరు పెద్ద అక్షరంతో ప్రారంభం కావాలి.',
    enterNumericValue: 'దయచేసి సంఖ్యాత్మక విలువను నమోదు చేయండి.',
    fruits: 'పండ్లు',
    vegetables: 'కూరగాయలు',
    dairyProducts: 'పాల ఉత్పత్తులు',
    startSelling: 'అమ్మడం ప్రారంభించండి',
    sellerCentral: 'సెల్లర్ సెంట్రల్',
    verifiedSeller: 'ధృవీకరిత అమ్మకందారుగా మారండి',
    partnerships: 'భాగస్వామ్యాలు',
    safePayments: 'సురక్షితమైన మరియు సులభమైన చెల్లింపులు',
    moneyBackPolicy: 'డబ్బు తిరిగి పొందే విధానం',
    onTimeShipping: 'సమయానికి షిప్పింగ్',
    productMonitoring: 'ఉత్పత్తి పర్యవేక్షణ సేవలు',
    cashOnDelivery: 'క్యాష్ ఆన్ డెలివరీ',
    aboutFreshFarms: 'Fresh Farms గురించి',
    bestPrices: 'ఉత్తమ ధరలు మరియు ఆఫర్లు',
    freeDelivery: 'ఉచిత డెలివరీ',
    greatDailyDeal: 'అద్భుతమైన రోజువారీ ఆఫర్',
    wideAssortment: 'విస్తృత ఎంపిక',
    easyReturns: 'సులభమైన రిటర్న్లు',
    orders50: '$50 లేదా అంతకంటే ఎక్కువ ఆర్డర్లు',
    inquiryTitle: 'మేము త్వరలో మీతో సంప్రదిస్తాము',
    firstName: 'మొదటి పేరు',
    lastName: 'చివరి పేరు',
    contactNumber: 'సంప్రదింపు నంబర్',
    message: 'సందేశం',
    send: 'పంపండి',
    messageSent: 'సందేశం పంపబడింది!',
    inquiryThanks: 'మీ విచారణకు ధన్యవాదాలు',
    loading: 'లోడవుతోంది...',
    exploreFreshProducts: 'తాజా ఉత్పత్తులు చూడండి',
    noProductsFound: 'ఉత్పత్తులు కనబడలేదు.',
    price: 'ధర',
    category: 'వర్గం',
    availability: 'లభ్యత',
    inStock: 'స్టాక్‌లో ఉంది',
    outOfStock: 'స్టాక్‌లో లేదు',
    kilogram: 'కిలోగ్రామ్',
    addToCart: 'కార్ట్‌కి జోడించండి',
    buyNow: 'ఇప్పుడే కొనండి',
    inquiry: 'విచారణ',
    addedToCartSuccess: 'కార్ట్‌లో విజయవంతంగా జోడించబడింది!',
    goToCart: 'కార్ట్‌కి వెళ్లండి',
    cartEmpty: 'కార్ట్ ఖాళీగా ఉంది',
    quantity: 'పరిమాణం',
    remove: 'తొలగించు',
    orderSummary: 'ఆర్డర్ సారాంశం',
    subtotal: 'ఉప మొత్తం',
    shippingFee: 'డెలివరీ ఫీజు',
    total: 'మొత్తం',
    proceedToCheckout: 'చెకౌట్ చేయండి',
    checkout: 'చెకౌట్',
    name: 'పేరు',
    phoneNumber: 'ఫోన్ నంబర్',
    pinAddressOnMap: 'మ్యాప్‌లో చిరునామాను గుర్తించండి',
    useCurrentLocation: 'ప్రస్తుత స్థానాన్ని వాడండి',
    addressDetails: 'చిరునామా వివరాలు',
    addressPlaceholder: 'మ్యాప్‌పై నొక్కండి లేదా పూర్తి చిరునామా టైప్ చేయండి...',
    placeOrder: 'ఆర్డర్ పెట్టండి',
    orderPlaced: 'మీ ఆర్డర్ విజయవంతంగా పూర్తైంది!',
    goHome: 'హోమ్‌కు తిరిగి వెళ్లండి',
    deliveryLocation: 'డెలివరీ స్థలం',
    joinAsRider: 'రైడర్‌గా చేరండి',
    riderLogin: 'డెలివరీ భాగస్వామి లాగిన్',
    consumerFarmerLogin: 'వినియోగదారు / రైతు లాగిన్'
  }
};

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key, fallback) => fallback || key
});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_KEY) || 'en');

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key, fallback = '') => translations[language]?.[key] || translations.en[key] || fallback || key
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
