name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Only trigger if changes happen in the backend folder
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create Deployment Package
        run: |
          cd backend
          zip -r ../backend-deploy.zip . -x "node_modules/*" ".env"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "freshfarm-backend"
          environment_name: "Freshfarm-backend-env"
          version_label: "backend-${{ github.sha }}"
          region: "ap-south-2"
          deployment_package: backend-deploy.zip
